### ISSUE TITLE
Proposal: version v1.0.0 refactoring

### ISSUE THREAD

**Issue by maekawataiki** [aws-samples/cost-effective-aws-deployment-of-comfyui#22]
## version v1.0.0 refactoring

(Initially considered to rewrite in typescript, but decided to keep python)

### Tasks
- [x] Split the monolithic stack into smaller constructs
- [x] Implement parameter handling using `parameter.ts`
- [x] Add snapshot test 

### References
- [AWS CDK Typescript Guide](https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-typescript.html)
- [AWS CDK language](https://docs.aws.amazon.com/cdk/v2/guide/work-with.html)
- [AWS CDK Best Practices](https://docs.aws.amazon.com/cdk/v2/guide/best-practices.html)
